### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by LI-ZHONG-BI** [a62527776a/vue-floating-action-button#1]
<template>
  <div class="user-Button">
    <vue-fab :mainBtnColor="mainBtnColor" @clickMainBtn="clickMainBtn">
      <fab-item v-for="(item, idx) in currentButton" :idx="idx" :key="idx" :title="item.BtnName" :color="item.IconCls" @clickItem="clickItem(item)">
      </fab-item>
    </vue-fab>
  </div>
</template>
<script>
import { mapState, mapActions } from 'vuex'
import VueFab from 'vue-float-action-button'
export default {
  name: 'userButton',
  data () {
    return {
      mainBtnColor: '#FF0099'
    }
  },
  components: {
    VueFab
  },
  computed: {
    ...mapState('user', ['currentButton'])
  },
  created () {
    const _this = this
    if (_this.currentButton === null || _this.currentButton.length === 0) {
      let currentButton = JSON.parse(sessionStorage.getItem('SET_LOGIN_CURRENTBUTTON'))
      if (!currentButton) currentButton = []
      _this.setCurrentButton(currentButton)
    }
  },
  methods: {
    ...mapActions('user', ['setCurrentButton']),
    clickItem (item) {
      console.log(item)
    },
    clickMainBtn: function () {
      console.log('clickMainBtn')
    }
  }
}
</script>

**Comment by a62527776a** [comment]
我出了一个严重性的问题 打包方式出错了
