### ISSUE TITLE
点击按钮有方框出现,可否不显示方框?

### ISSUE THREAD

**Issue by Sforllln** [a62527776a/vue-floating-action-button#10]
如题

**Comment by a62527776a** [comment]
如果指的是文字提示的话
fab-item组件不传title参数则不会展示title框
如果指的是别的 请截图描述一下

**Comment by Sforllln** [comment]
[SVID_20190517_140452_1.zip](https://github.com/a62527776a/vue-floating-action-button/files/3190104/SVID_20190517_140452_1.zip)

- 这是我录制的屏幕视频, 我这边是在手机端显示的

**Comment by Sforllln** [comment]
PC 上面点击 好像没有这个情况

**Comment by a62527776a** [comment]
好 我检查一下

**Comment by Sforllln** [comment]
thanks  你这个玩意很棒 -.=

**Comment by a62527776a** [comment]
你好，能提供一下机型信息嘛 我暂时没能在手头的小米MAX上复现

**Comment by Sforllln** [comment]
华为荣耀v10 ,oppoe A77 都这样啊

**Comment by Sforllln** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/20089011/57911669-ef90b880-78ba-11e9-8ce7-b787187bf855.jpg)

用pc  改成手机大小也会这样..

**Comment by Sforllln** [comment]
浏览器 是  Google Chrome

**Comment by a62527776a** [comment]
好的 我在检查一下

**Comment by a62527776a** [comment]
你有demo页面嘛？
我怀疑是-webkit-tap-highlight-color这个css属性的问题
不过我并没有设置这个属性
我的demo页在几台测试机上并没有复现这种情况
PC浏览器修改为手机大小也并未出现
我想可能是全局的-webkit-tap-highlight-color污染到了这个地方
如果有demo页的话我可以更准确的定位问题

**Comment by Sforllln** [comment]
你好.还确实是这个属性属性 污染了,
我在外部添加了 : -webkit-tap-highlight-color: transparent;
就没有这个方框了.
