### ISSUE TITLE
成功部署，但首页部分元素出现异常

### ISSUE THREAD

**Issue by tchangeme** [a62527776a/vue-floating-action-button#2]
您好非常感谢，通过npm 安装后成功在自己已有网站的app.vue页面上添加如下代码，实现悬浮菜单功能；
`        //- app-fab
`        //- app-fab
        <vue-fab ref="vuefab"  icon="fingerprint" :mainBtnColor="mainBtnColor" style="right: 56%;transition: all .5s cubic-bezier(.18,.89,.58,1.26)" size="big" :globalOptions="{spacing: 50,delay: 0.1}" :activeIcon="activeIcon" :fabAnimateBezier="fabAnimateBezier" :fabAutoHideAnimateModel="'alive'" fabItemAnimate="alive">
            <fab-item  @clickItem="clickItemA" :idx="0"  titleColor="#FFF" title="任务" titleBgColor="#6c757d" color='#fd7e14' icon="done" />
            <fab-item  @clickItem="clickItemB" :idx="1"  titleColor="#FFF" title="团队" titleBgColor="#6c757d" color='#e83e8c' icon="group" />
            <fab-item  @clickItem="clickItemC" :idx="2"  titleColor="#FFF" title="公会" titleBgColor="#6c757d" color='#6610f2' icon="public" />
            <fab-item  @clickItem="clickItemD" :idx="3"  titleColor="#FFF" title="挑战" titleBgColor="#6c757d" color='#007bff' icon="score" />
        </vue-fab>
        </vue-fab>
            <vue-fab   :mainBtnColor="'#ff9900'" :icon="'face'" @clickMainBtn='showAvatar("backgrounds", "2019")' :menu="[]" style="right: 80%;transition: all .5s cubic-bezier(.18,.89,.58,1.26)">
        </vue-fab>
        </vue-fab>
            <vue-fab   :mainBtnColor="'#dc3545'" :icon="'swap_horiz'" @clickMainBtn="clickMainBtnB" :menu="[]" style="right: 30%;transition: all .5s cubic-bezier(.18,.89,.58,1.26)">
        </vue-fab>`

但是存在以下2个问题：
1、首页部分元素，出现错位。如下图所示：
[元素出现错误](https://snag.gy/JPI5yX.jpg)
将上述代码注释掉后，恢复正常
https://snag.gy/julgKh.jpg
2、首页出现双滚动条，如下图所示
[首页双滚动条](https://snag.gy/w9o6R8.jpg)
将上述代码注释掉后，恢复正常
https://snag.gy/ZdXP6U.jpg

**Comment by a62527776a** [comment]
感谢反馈 元素错误应该是css样式污染 我处理下
双滚动条暂时无法复现 能否给个链接我查看下具体场景

**Comment by a62527776a** [comment]
> 您好非常感谢，通过npm 安装后成功在自己已有网站的app.vue页面上添加如下代码，实现悬浮菜单功能；
> ` //- app-fab` //- app-fab
> 
> <fab-item @clickItem="clickItemA" :idx="0" titleColor="#FFF" title="任务" titleBgColor="#6c757d" color='#fd7e14' icon="done" />
> <fab-item @clickItem="clickItemB" :idx="1" titleColor="#FFF" title="团队" titleBgColor="#6c757d" color='#e83e8c' icon="group" />
> <fab-item @clickItem="clickItemC" :idx="2" titleColor="#FFF" title="公会" titleBgColor="#6c757d" color='#6610f2' icon="public" />
> <fab-item @clickItem="clickItemD" :idx="3" titleColor="#FFF" title="挑战" titleBgColor="#6c757d" color='#007bff' icon="score" />
> 
> 
> <vue-fab :mainBtnColor="'#ff9900'" :icon="'face'" @clickMainBtn='showAvatar("backgrounds", "2019")' :menu="[]" style="right: 80%;transition: all .5s cubic-bezier(.18,.89,.58,1.26)">
> 
> 
> <vue-fab :mainBtnColor="'#dc3545'" :icon="'swap_horiz'" @clickMainBtn="clickMainBtnB" :menu="[]" style="right: 30%;transition: all .5s cubic-bezier(.18,.89,.58,1.26)">
> `
> 
> 但是存在以下2个问题：
> 1、首页部分元素，出现错位。如下图所示：
> [元素出现错误](https://snag.gy/JPI5yX.jpg)
> 将上述代码注释掉后，恢复正常
> https://snag.gy/julgKh.jpg
> 2、首页出现双滚动条，如下图所示
> [首页双滚动条](https://snag.gy/w9o6R8.jpg)
> 将上述代码注释掉后，恢复正常
> https://snag.gy/ZdXP6U.jpg

最新的0.4.3版本处理了部分元素错位的问题

**Comment by tchangeme** [comment]
> 感谢反馈 元素错误应该是css样式污染 我处理下
> 双滚动条暂时无法复现 能否给个链接我查看下具体场景

你好地址为https://2change.club，需要麻烦您自己创建个账号，试下。另外还想咨询个问题：如何让悬浮按钮在页面上居中显示呢？通过跳转right 的百分比，无法确保100%居中；

**Comment by a62527776a** [comment]
> > 感谢反馈 元素错误应该是css样式污染 我处理下
> > 双滚动条暂时无法复现 能否给个链接我查看下具体场景
> 
> 你好地址为[https://2change.club，需要麻烦您自己创建个账号，试下。另外还想咨询个问题：如何让悬浮按钮在页面上居中显示呢？通过跳转right](https://2change.club%EF%BC%8C%E9%9C%80%E8%A6%81%E9%BA%BB%E7%83%A6%E6%82%A8%E8%87%AA%E5%B7%B1%E5%88%9B%E5%BB%BA%E4%B8%AA%E8%B4%A6%E5%8F%B7%EF%BC%8C%E8%AF%95%E4%B8%8B%E3%80%82%E5%8F%A6%E5%A4%96%E8%BF%98%E6%83%B3%E5%92%A8%E8%AF%A2%E4%B8%AA%E9%97%AE%E9%A2%98%EF%BC%9A%E5%A6%82%E4%BD%95%E8%AE%A9%E6%82%AC%E6%B5%AE%E6%8C%89%E9%92%AE%E5%9C%A8%E9%A1%B5%E9%9D%A2%E4%B8%8A%E5%B1%85%E4%B8%AD%E6%98%BE%E7%A4%BA%E5%91%A2%EF%BC%9F%E9%80%9A%E8%BF%87%E8%B7%B3%E8%BD%ACright) 的百分比，无法确保100%居中；

关于如何居中
`
right: 50%
margin-right: -24px;
`
margin-right的值是节点宽度 / 2 我看贵应用展示在中间的fab为48px的宽度 所以margin-right应为-24px
并且right为50%

**Comment by a62527776a** [comment]
[居中处理](https://i.loli.net/2019/02/23/5c7100e06ad76.png)

**Comment by tchangeme** [comment]
非常感谢，样式错位，双滚动条的问题已经解决了，不过按钮显示在中间，我加了margin-right:-24px; 之后没起作用；

`        //- app-fab
        <vue-fab ref="vuefab"  icon="fingerprint" :mainBtnColor="mainBtnColor" style="right:50% margin-right:-24px;transition: all .5s cubic-bezier(.18,.89,.58,1.26)" size="big" :globalOptions="{spacing: 50,delay: 0.1}" :activeIcon="activeIcon" :fabAnimateBezier="fabAnimateBezier" :fabAutoHideAnimateModel="'alive'" fabItemAnimate="alive">
            <fab-item  @clickItem="clickItemA" :idx="0"  titleColor="#FFF" title="任务" titleBgColor="#6c757d" color='#fd7e14' icon="done" />
            <fab-item  @clickItem="clickItemB" :idx="1"  titleColor="#FFF" title="团队" titleBgColor="#6c757d" color='#e83e8c' icon="group" />
            <fab-item  @clickItem="clickItemC" :idx="2"  titleColor="#FFF" title="公会" titleBgColor="#6c757d" color='#6610f2' icon="public" />
            <fab-item  @clickItem="clickItemD" :idx="3"  titleColor="#FFF" title="挑战" titleBgColor="#6c757d" color='#007bff' icon="score" />`

**Comment by tchangeme** [comment]
不好意思，是我的问题，我写错了；非常感谢，完美解决了我的问题；

**Comment by a62527776a** [comment]
> 非常感谢，样式错位，双滚动条的问题已经解决了，不过按钮显示在中间，我加了margin-right:-24px; 之后没起作用；
> 
> ` //- app-fab <vue-fab ref="vuefab" icon="fingerprint" :mainBtnColor="mainBtnColor" style="right:50% margin-right:-24px;transition: all .5s cubic-bezier(.18,.89,.58,1.26)" size="big" :globalOptions="{spacing: 50,delay: 0.1}" :activeIcon="activeIcon" :fabAnimateBezier="fabAnimateBezier" :fabAutoHideAnimateModel="'alive'" fabItemAnimate="alive"> <fab-item @clickItem="clickItemA" :idx="0" titleColor="#FFF" title="任务" titleBgColor="#6c757d" color='#fd7e14' icon="done" /> <fab-item @clickItem="clickItemB" :idx="1" titleColor="#FFF" title="团队" titleBgColor="#6c757d" color='#e83e8c' icon="group" /> <fab-item @clickItem="clickItemC" :idx="2" titleColor="#FFF" title="公会" titleBgColor="#6c757d" color='#6610f2' icon="public" /> <fab-item @clickItem="clickItemD" :idx="3" titleColor="#FFF" title="挑战" titleBgColor="#6c757d" color='#007bff' icon="score" />`

我观察到style=right:50% margin-right:-24px中间少个一个;号 所以并没有起效果
margin-right因为24px 我写错了

**Comment by a62527776a** [comment]
> 不好意思，是我的问题，我写错了；非常感谢，完美解决了我的问题；

感谢您的支持

**Comment by tchangeme** [comment]
方便在帮我看个其他问题吗，我的导航菜单，点击下拉菜单后，页面刷新，但是菜单不会自动收回去，需要调整哪里呢

**Comment by tchangeme** [comment]
嗯，是的

**Comment by tchangeme** [comment]
嗯，是的

**Comment by tchangeme** [comment]
嗯，是的

**Comment by a62527776a** [comment]
> 方便在帮我看个其他问题吗，我的导航菜单，点击下拉菜单后，页面刷新，但是菜单不会自动收回去，需要调整哪里呢；这个是我的网站的问题；

你的意思是？ 鼠标滑倒商店 => 任务 点击之后 路由跳转了 菜单还是展示着吗？

**Comment by tchangeme** [comment]
> > 方便在帮我看个其他问题吗，我的导航菜单，点击下拉菜单后，页面刷新，但是菜单不会自动收回去，需要调整哪里呢；这个是我的网站的问题；
> 
> 你的意思是？ 鼠标滑倒商店 => 任务 点击之后 路由跳转了 菜单还是展示着吗？

嗯，是的，就是这个问题；

**Comment by a62527776a** [comment]
> > > 方便在帮我看个其他问题吗，我的导航菜单，点击下拉菜单后，页面刷新，但是菜单不会自动收回去，需要调整哪里呢；这个是我的网站的问题；
> > 
> > 
> > 你的意思是？ 鼠标滑倒商店 => 任务 点击之后 路由跳转了 菜单还是展示着吗？
> 
> 嗯，是的，就是这个问题；

跳转到不同的路由之后看似是刷新了页面 实际上并没有刷新

而css ::hover的又不好控制
我推荐使用js去控制 菜单栏的隐藏和展示

**Comment by tchangeme** [comment]
好的多谢指导
