### ISSUE TITLE
Uncaught TypeError: t.binding.value is not a function

### ISSUE THREAD

**Issue by elmawardy** [a62527776a/vue-floating-action-button#24]
I get this error in console while trying to press on the screen after opening a vuetify modal with autocomplete component inside

vue-fab.js?8cf7:1 Uncaught TypeError: t.binding.value is not a function
    at e.listenClick (vue-fab.js?8cf7:1)
    at eval (vue-fab.js?8cf7:1)

**Comment by a62527776a** [comment]
Will it make it unusable?

I found the problem, but I don’t want to release a new version if it will not have very serious consequences

**Comment by a62527776a** [comment]
Thanks for your Issues

**Comment by a62527776a** [comment]
Least version fixed this program.
