### ISSUE TITLE
能还改变子菜单弹出方向？

### ISSUE THREAD

**Issue by Joyeah** [a62527776a/vue-floating-action-button#25]
目前是不是只能在页面底部、向上弹出？否则改变定位和弹出方向？

**Comment by a62527776a** [comment]
最新的0.7.7版本增加了展开方向的配置，目前仅支持向上 或者向下展开 

可以通过文档https://a62527776a.github.io/unfoldDirection.html查看

改变定位可以自行使用top left属性为<vue-fab />组件定位
