### ISSUE TITLE
size为"big"时，fab-item挨在一起了

### ISSUE THREAD

**Issue by Haiwar** [a62527776a/vue-floating-action-button#38]
![image](https://user-images.githubusercontent.com/35055270/132626045-167aa116-f0e9-4849-977e-f60644284621.png)

**Comment by a62527776a** [comment]
size="big" 
      :globalOptions="{ spacing: 50, delay: 0.05 }" 

注意配置一下globalOptions的spacing参数

**Comment by a62527776a** [comment]
<vue-fab 
      icon="menu" 
      size="big" 
      :globalOptions="{ spacing: 50, delay: 0.05 }" 
      >

**Comment by a62527776a** [comment]
<vue-fab 
      icon="menu" 
      size="big" 
      :globalOptions="{ spacing: 50, delay: 0.05 }" 
      >
