### ISSUE TITLE
removeEventListener 报错 bug

### ISSUE THREAD

**Issue by YLD10** [a62527776a/vue-floating-action-button#5]
[Vue warn]: Error in destroyed hook: "TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present."
![image](https://user-images.githubusercontent.com/18281925/54692044-4b5eef80-4b5f-11e9-9f70-ee20768cecd9.png)

**Comment by a62527776a** [comment]
感谢您的反馈，最新的0.4.5版本解决了由这个BUG引起的scrollAutoHide属性无效的问题
[demo](http://htmlpreview.github.io/?https://github.com/a62527776a/vue-fab/blob/master/demo/dist/index.html)
