### ISSUE TITLE
vue-fab组件的滑动隐藏“方向”可控吗？

### ISSUE THREAD

**Issue by Karma1996** [a62527776a/vue-floating-action-button#6]
vue-fab组件默认的滑动隐藏手势为“向上隐藏，向下显示”，请问这个手势方向可以控制吗？
![image](https://user-images.githubusercontent.com/37733288/55217262-06f7e180-523a-11e9-873b-6ee47410f0b4.png)

**Comment by a62527776a** [comment]
在最新的@0.5.5版本中添加了一个控制滑动方向隐藏的参数‘autoHideDirection’您的需求可以通过填写值为down实现 具体demo可以查看http://htmlpreview.github.io/?https://github.com/a62527776a/vue-floating-action-button/blob/master/demo/dist/index.html
demo代码可以通过https://github.com/a62527776a/vue-floating-action-button/blob/master/demo/App.vue#L55的55行查看

**Comment by Karma1996** [comment]
感谢
