### ISSUE TITLE
vue-fab与keep-alive相关问题

### ISSUE THREAD

**Issue by Karma1996** [a62527776a/vue-floating-action-button#8]
项目没有keep-alive时：
![image](https://user-images.githubusercontent.com/37733288/56270586-0c559700-6129-11e9-8790-d3594dd146e0.png)
运行结果：
![noKeepAlive](https://user-images.githubusercontent.com/37733288/56270981-fbf1ec00-6129-11e9-88df-78f74d48fcb8.gif)

项目增加keep-alive时：
![image](https://user-images.githubusercontent.com/37733288/56271060-293e9a00-612a-11e9-884f-36411ed81c37.png)
运行结果：
![keepAlive](https://user-images.githubusercontent.com/37733288/56271075-2f347b00-612a-11e9-8285-76923c448675.gif)

现象：增加keep-alive后，vue-fab手势不响应。控制台也没有报错。

**Comment by a62527776a** [comment]
查到是在deactivated钩子中卸载了相关事件，但在activated中没有监听相关事件导致的BUG
最新的0.6.0版本中在activated生命周期中监听了相关事件，修复了这个BUG

**Comment by Karma1996** [comment]
非常感谢
